services:
  app:
    container_name: capture_app
    build: .
    ports:
      - '8080:3000'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: capture_app_mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: capture_app_db

    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD}']
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
